### PR TITLE
hotfix/add clang format

### PR DESCRIPTION
**Pull request by xmba15**
- related to [this issue](https://github.com/Autoware-AI/core_perception/issues/8) I added .clang-format file
- add roslint for lidar_shape_estimation package, cleaned trailing spaces

### CODE REVIEW

**Comment by xmba15** [comment]
@JWhitleyWork I added .clang-format and added roslint option for lidar_shape_estimate package only, but seems like the CUDA CI workflow failed for a warning treated as an error though the same warning occurred for Cross CI workflow. Is it expected behavior for the current setting?

**Comment by JWhitleyWork** [comment]
@xmba15 I'm actually not sure why it passed in the Native CI workflow. This should have failed. Adding `roslint` does not reformat the files, it just gives errors when they are not formatted correctly - this is the cause of the test failure. If you intend to add `roslint` to `lidar_shape_estimation`, you must also apply all of the recommendations from `roslint` (most of which are solved by applying the `.clang-format` file using `clang-format`).

Additionally, you must sign your commits. See the DCO check Details link for more information.

**Comment by xmba15** [comment]
@JWhitleyWork I applied the clang-format to the source code of lidar_shape_estimation, and added signoff for my commits in this PR. Please let me know if more modifications needed.

**Comment by xmba15** [comment]
I have double-check about applying clang-formatter with the newly-added .clang-format into source files of lidar_shape_estimate but the CUDA CI workflow still failed. The log is stored in roslint-lidar_shape_estimation.xml that I cannot access through CI container (maybe only because I don't know how?). Let me spend time to build everything locally and come back later.

**Comment by JWhitleyWork** [comment]
@xmba15 You are still missing the commit signatures.

**Comment by JWhitleyWork** [comment]
@xmba15 There are also still linter errors. Please run `colcon build` and `colcon test` and then `colcon test-result --verbose` to see what errors were reported.

**Comment by xmba15** [comment]
@JWhitleyWork sorry for the late reply. I think the current commits fixed the issues for roslint.
but DCO is still blocking me, do I need to sign off for 8577dd6ffd20b9d2cba5ecd59d1000fc3d800ed as suggested by DCO?

**Comment by JWhitleyWork** [comment]
@xmba15 Yes, all commits must be signed.

**Comment by JWhitleyWork** [comment]
LGTM. I'll merge after CI passes.

**Pull request merged**
